#!/bin/bash

# ******************************
# *** Welcome to the myshell ***
# ******************************

###VARIABLES###

###FUNCTIONS###

sub_command=$1
version=1.0.0

if [ -z $sub_command ]; then
    echo "Usage: msh <command>"
    echo "Run 'msh help' for more information"
    exit 1
fi

echo "myshell version $version"

# call the function in the setup file
source src/setup
# run the setup function

function setup {
    echo "setup $1"
}

setup $2