#!/bin/bash

# ***************************************
# *** Run myshell in development mode ***
# ***************************************

# Compile program
python compile.py -o out/msh

# check if file exists
if [ ! -f out/msh ]; then
    echo "Error: Compilation failed"
    exit 1
fi

# Run program
./out/msh $* -dev