#!/bin/bash

echo "                          __         ____"
echo "    ____ ___  __  _______/ /_  ___  / / /"
echo "   / __  __ \/ / / / ___/ __ \/ _ \/ / / "
echo "  / / / / / / /_/ (__  ) / / /  __/ / /  "
echo " /_/ /_/ /_/\__, /____/_/ /_/\___/_/_/   "
echo "           /____/ Update"
echo ""


cd $HOME/.myshell
if [ -f "bin/msh-update-runner" ]; then
    rm bin/msh-update-runner
fi
curl -s https://raw.githubusercontent.com/cophilot/msh/main/update-runner > bin/msh-update-runner

./bin/msh-update-runner
