#!/bin/bash

echo "                          __         ____"
echo "    ____ ___  __  _______/ /_  ___  / / /"
echo "   / __  __ \/ / / / ___/ __ \/ _ \/ / / "
echo "  / / / / / / /_/ (__  ) / / /  __/ / /  "
echo " /_/ /_/ /_/\__, /____/_/ /_/\___/_/_/   "
echo "           /____/ Update"
echo ""

curl -s https://raw.githubusercontent.com/cophilot/msh/main/install | bash -s
