#!/bin/bash

###START###

function alias {
    echo "Not implemented: alias"
    exit 1
}

# Print help for the alias command
function alias_help {
    echo "  [alias|a] description"
}

# Short form of the alias command
function a {
    alias $*
}

###END###