#!/bin/bash

###START###

function alias_command {
    require_dir $HOME_DIR
    script_name=${VALUES[0]}
    cmd_name=${VALUES[1]}

    if [ -z "$script_name" ]
    then
        log "Please provide the name for the new-script"
        myexit 1
    fi
    if [ -z "$cmd_name" ]; then
        log "Please provide the command to create an alias for"
        myexit 1
    fi

    check_if_command_exists $new_command
    description="Alias for '$cmd_name'"
    cmd2="$cmd_name \$*"
    cmd1='echo "$cmd2"'

    create_new_script $SCRIPTS_DIR $script_name "$description" "$cmd1" "$cmd2"

    log "Alias script '$script_name' created ($SCRIPTS_DIR/$script_name)"
}

# Print help for the alias command
function alias_help {
    log "  alias|a <new-script> <command> - Create a new alias for a command"
    log "      new-command - The name of the new command to create"
    log "      command - The command to create an alias for"
    log ""
}

# Short form of the alias command
function a_command {
    alias_command $*
}

###END###