#!/bin/bash

###START###

# Edit a script in the editor
function edit_command {
	require_dir $HOME_DIR
	edcom=$(get_editor_command)
	script_name=${VALUES[0]}

	if [ -z "$script_name" ]; then
		$edcom $HOME_DIR
		myexit 0
	fi

	file_location=$(resolve_script_name "$script_name")

	if [ -z "$file_location" ]; then
		log_e "Script '$script_name' not found"
		myexit 1
	fi

	$edcom $file_location
}

# Print help for the edit command
function edit_help {
	log "  edit|e [script-name] - Open a specified or all scripts in the editor"
	log "      script-name - If provided, the script with the specified name will be opened in the editor"
	log ""
}

# Short form of the code command
function e_command {
	edit_command $*
}

###END###
