#!/bin/bash

###START###

# Edit a script in the editor
function edit_command {
	require_dir $HOME_DIR
	script_name=${VALUES[0]}
	echo "HALLLOOOO"

	edcom=$(get_editor_command)
	if [ "$(is_flag_specified '-quick' '-q')" == "true" ]; then
		edcom=$(get_quick_editor_command)
	fi

	if [ -z "$script_name" ]; then
		$edcom $HOME_DIR
		myexit 0
	fi

	echo "Script name: $script_name"
	file_location=$(resolve_script_name_with_py "$script_name")

	echo "File location: $file_location"

	if [ -z "$file_location" ]; then
		log_e "Script '$script_name' not found"
		myexit 1
	fi

	$edcom $file_location
}

# Print help for the edit command
function edit_help {
	log "  edit|e [script-name] [flags] - Open a specified or all scripts in the editor"
	log "      script-name - If provided, the script with the specified name will be opened in the editor"
	log "      Flags:"
	log "          -quick|-q - Use the quick editor command"
	log ""
}

# Short form of the code command
function e_command {
	edit_command $*
}

###END###
