#!/bin/bash

###START###

# Get help for myshell
function help {
    echo "                          __         ____"
    echo "    ____ ___  __  _______/ /_  ___  / / /"
    echo "   / __  __ \/ / / / ___/ __ \/ _ \/ / / "
    echo "  / / / / / / /_/ (__  ) / / /  __/ / /  "
    echo " /_/ /_/ /_/\__, /____/_/ /_/\___/_/_/   "
    echo "           /____/ Help center"
    echo ""
    echo "Usage: msh <command>"
    echo ""
    echo "<...> = required"
    echo "[...] = optional"
    echo ""
    echo "Commands:"
    alias_help 
    edit_help
    help_help
    list_help
    version_help
}

# Print help for the help command
function help_help {
    #echo "  <help|h> [command] - Get help for myshell"
    #echo "      command - The command to get help for"
    echo "  <help|h> - Get help for myshell"
    echo ""
}

function h {
    help $*
}

###END###