#!/bin/bash

###START###

# Get help for myshell
function help_command {
    log "                          __         ____"
    log "    ____ ___  __  _______/ /_  ___  / / /"
    log "   / __  __ \/ / / / ___/ __ \/ _ \/ / / "
    log "  / / / / / / /_/ (__  ) / / /  __/ / /  "
    log " /_/ /_/ /_/\__, /____/_/ /_/\___/_/_/   "
    log "           /____/ Help center"
    log ""
    log "Usage: msh <command>"
    log ""
    log "<...> = required"
    log "[...] = optional"
    log ""
    log "Commands:"
    alias_help 
    collection_help
    edit_help
    help_help
    list_help
    new_help
    print_help
    version_help
    log " Global flags (apply to all commands):"
    log "  --quiet|--q - Do not print any output"
}

# Print help for the help command
function help_help {
    #log "  help|h [command] - Get help for myshell"
    #log "      command - The command to get help for"
    log "  help|h - Get help for myshell"
    log ""
}

function h_command {
    help_command $*
}

###END###