#!/bin/bash

###START###

# Print the manual for a script
function manual_command {
	require_dir $HOME_DIR
	script_name=${VALUES[0]}

	if [ -z "$script_name" ]; then
		log_e "Please provide the name of the script to get the manual for"
		myexit 1
	fi

	file_location=$(resolve_script_name "$script_name")

	if [ -z "$file_location" ]; then
		log_e "Script '$script_name' not found"
		myexit 1
	fi
	content=$(cat $file_location)

	manual_text=$(echo "$content" | grep -E "###.*" | sed -e 's/###//g')
	description=$(grep -m 1 -o "#??.*" <<<"$content" | cut -c4-)

	if [ -z "$manual_text" ] && [ -z "$description" ]; then
		log "No manual found for script '$script_name'"
		myexit 0
	fi

	if [ -n "$description" ]; then
		log "$description"
	fi

	if [ "$(is_flag_specified '-print' '-p')" == "true" ]; then
		print_script_content $file_location
		log ""
		log "---"
	fi

	log "$manual_text"

	run_if_flag_is_specified $file_location
}

# Print help for the manual command
function manual_help {
	log "  manual|m <script> [flags] - Get the manual for the script"
	log "      script - The name of the script to get the manual for"
	log "      Flags:"
	log "          -print|-p - Show the collection of the scripts"
	log "          -run|-r - Show the collection of the scripts"
	log ""
}

# Short form of the manual help command
function m_help {
	manual_help $*
}

# Short form of the manual command
function m_command {
	manual_command $*
}

###END###
