#!/bin/bash

###START###

# Create a new script
function new_command {
	require_dir $HOME_DIR
	script_name=${VALUES[0]}
	if [ -z "$script_name" ]; then
		log_e "Please provide the name for the new script"
		myexit 1
	fi

	collection_name=${VALUES[1]}
	if [ -z "$collection_name" ]; then
		collection_name=$(get_default_collection)
	elif [ ! -d "$HOME_DIR/$collection_name" ]; then
		log_e "Collection '$collection_name' does not exist"
		myexit 1
	fi

	check_if_command_exists $script_name

	sc_dir="$HOME_DIR/$collection_name"

	add_manual="false"
	if [ "$(is_flag_specified '-man' '-m')" == "true" ]; then
		add_manual="true"
	fi

	create_new_script $sc_dir $script_name "" "" "" $add_manual

	log "Script '$script_name' created ($sc_dir/$script_name)"

	if [ "$(is_flag_specified '-edit' '-e')" == "true" ]; then
		edcom=$(get_editor_command)
		$edcom $sc_dir/$script_name
	fi
	if [ "$(is_flag_specified '-quick-edit' '-qe')" == "true" ]; then
		edcom=$(get_quick_editor_command)
		$edcom $sc_dir/$script_name
	fi
}

# Print help for the new command
function new_help {
	log "  new|n <new-script> [collection-name] [flags]- Create a new script"
	log "      script-name - The name of the script to create"
	log "      collection-name - The name of the collection to add the script to. The default collection can be set in the config"
	log "      Flags:"
	log "          -edit|-e - Open the script in the editor after creation"
	log "          -man|-m - Add a manual to the script"
	log "          -quick-edit|-qe - Open the script in the editor after creation, using the quick editor command"
	log ""
}

# Short form of the new command
function n_command {
	new_command $*
}

###END###
