#!/bin/bash

###START###

# Print the contents of a script
function print_command {
	require_msh_home_dir

	p_comm=$(get_print_command)
	script_name=${VALUES[0]}

	if [ -z "$script_name" ]; then
		log_e "Please provide the name of the script to print"
		myexit 1
	fi

	file_location=$(resolve_script_name "$script_name")

	if [ -z "$file_location" ]; then
		log_e "Script '$script_name' not found"
		myexit 1
	fi

	log "File: $file_location"
	log "---"

	print_script_content $file_location

	run_if_flag_is_specified $file_location
}

# Print help for the print command
function print_help {
	log "  print|p <script-name> [flags] - Print the contents of a script"
	log "      script-name - The name of the script to print"
	log "      Flags:"
	log "          -run|-r - Run the script after printing"
	log ""
}

# Autocomplete helper for the print command. This gets called by the autocomplete function in src/commands/autocomplete.sh
function print_autocomplete_helper {
	echo "
-run
<SCRIPTS>
"
}

# Short form of the print help command
function p_help {
	print_help $*
}

# Short form of the print command
function p_command {
	print_command $*
}

###END###
