#!/bin/bash

###START###

function remove_command {
    require_dir $HOME_DIR
    script_name=${VALUES[0]}
    
    if [ -z "$script_name" ]
    then
        logE "Please provide the name of the script to remove"
        myexit 1
    fi

    file_location=$(resolve_script_name "$script_name")

    if [ -z "$file_location" ]; then
        logE "Script '$script_name' not found"
        myexit 1
    fi

    if [ "$(is_flag_specified '-force' '-f')" == "true" ]
    then
        rm -f $file_location
        echo "Script '$script_name' removed"
        myexit 0
    fi

    mkdir -p $HOME_DIR/.trash

    mv $file_location $HOME_DIR/.trash/$script_name
    echo "Command '$script_name' moved to trash"
}

# Print help for the remove command
function remove_help {
    log "  remove|rm <script> [flags] - Remove a script"
    log "      script - The name of the script to remove"
    log "      Flags:"
    log "          -force|-f - Remove script without storing it in the trash"
    log ""
}

# Short form of the remove command
function rm_command {
    remove_command $*
}

###END###