#!/bin/bash

###START###

function remove_command {
    logE "Not implemented: remove"
    myexit 1
}

# Print help for the remove command
function remove_help {
    log "  remove|rm <command> - Remove a command"
    log "      command - The name of the command to remove"
    log ""
}

# Short form of the remove command
function rm_command {
    remove_command $*
}

###END###