#!/bin/bash

###START###

function update {
	logE "Not implemented: update"
	myexit 1
}

# Print help for the update command
function update_help {
	log "  [update|u] description"
}

# Short form of the update command
function u {
	update $*
}

###END###
