#!/bin/bash

###START###

# Print the version of the myshell
function version_command {
    log "                          __         ____"
    log "    ____ ___  __  _______/ /_  ___  / / /"
    log "   / __  __ \/ / / / ___/ __ \/ _ \/ / / "
    log "  / / / / / / /_/ (__  ) / / /  __/ / /  "
    log " /_/ /_/ /_/\__, /____/_/ /_/\___/_/_/   "
    log "           /____/ v$version"
    log ""
}

function v_command {
    version_command $*
}

# Print help for the version command
function version_help {
    log "  version|v - Print the version of myshell"
    log ""
}


###END###