#!/bin/bash

###START###

function collection_new_command {
	coll_name=${VALUES[1]}

	if [ -z "$coll_name" ]; then
		logE "Please provide the name for the new collection"
		myexit 1
	fi

	if [ "$coll_name" == "bin" ]; then
		logE "Collection name 'bin' is reserved"
		myexit 1
	fi

	if [ "$coll_name" == "scripts" ]; then
		logE "Collection name 'scripts' is reserved"
		myexit 1
	fi

	if [[ $coll_name == .* ]]; then
		logE "Collection name cannot start with a dot"
		myexit 1
	fi

	all_collection=$(get_all_collections)
	for collection in ${all_collection[@]}; do
		if [ "$collection" == "$coll_name" ]; then
			logE "Collection '$coll_name' already exists"
			myexit 1
		fi
	done

	mkdir -p $HOME_DIR/$coll_name
	add_collection_to_mshrc $coll_name
	log "Collection '$coll_name' created ($HOME_DIR/$coll_name)"
	log "Run 'source $BASHRC_FILE' to activate the new collection"
}

# Print help for the collectionnew command
function collection_new_help {
	log "  collection|c new|n <collection-name> - Create a new collection"
	log "      collection-name - The name of the collection to create"
	log ""
}

# Short form of the collectionnew command
function collection_n_command {
	collection_new_command $*
}

###END###
