#!/bin/bash

###START###

# The collection sub-category of commands
function collection_command {
	comm=${VALUES[0]}
	if [ -z "$comm" ]; then
		log_e "Please provide a sub-command"
		myexit 1
	fi
	comm_fn="collection_${comm}_command"
	dynamic_run_and_exit $comm_fn $args

	log_e "Command not found: collection $comm"
	myexit 1
}

# Print help for the collection command
function collection_help {
	collection_clone_help
	collection_list_help
	collection_new_help
}

# Short form of the collection command
function c_command {
	collection_command $*
}

###END###
