#!/bin/bash

###START###

# Create a new collection
function collection_new_command {
	coll_name=${VALUES[1]}

	if [ -z "$coll_name" ]; then
		log_e "Please provide the name for the new collection"
		myexit 1
	fi

	if [ "$coll_name" == "bin" ]; then
		log_e "Collection name 'bin' is reserved"
		myexit 1
	fi

	if [ "$coll_name" == "scripts" ]; then
		log_e "Collection name 'scripts' is reserved"
		myexit 1
	fi

	if [[ $coll_name == .* ]]; then
		log_e "Collection name cannot start with a dot"
		myexit 1
	fi

	all_collection=$(get_all_collections)
	for collection in ${all_collection[@]}; do
		if [ "$collection" == "$coll_name" ]; then
			log_e "Collection '$coll_name' already exists"
			myexit 1
		fi
	done

	executable_folder="$coll_name"
	if [ "$(is_flag_specified '-bin' '-b')" == "true" ]; then
		executable_folder="$coll_name/bin"
	fi
	mkdir -p $HOME_DIR/$executable_folder

	add_collection_to_mshrc $executable_folder
	log "Collection '$coll_name' created ($HOME_DIR/$coll_name)"
	log "Run 'source $BASHRC_FILE' to activate the new collection"
}

# Print help for the collectionnew command
function collection_new_help {
	log "  collection|c new|n <collection-name> - Create a new collection"
	log "      collection-name - The name of the collection to create"
	log "      Flags:"
	log "          -bin|-b - Create a bin directory within the collection"
	log ""
}

# Short form of the collectionnew command
function collection_n_command {
	collection_new_command $*
}

###END###
