#!/bin/bash

###START###

# List all collections
function collection_list_command {

	print_raw="$(is_flag_specified '-raw' '-r')"
	all_collection=$(get_all_collections)
	if [ ${#all_collection} -eq 0 ]; then
		if [ "$print_raw" == "false" ]; then
			log "No collections found"
		fi
		myexit 0
	fi

	if [ "$print_raw" == "false" ]; then
		log "Collections:"
	fi

	for collection in ${all_collection[@]}; do
		# check if collection is a git repository
		url=""
		if [ -d "$HOME_DIR/$collection/.git" ]; then
			url=$(git -C $HOME_DIR/$collection remote get-url origin)
			url="[$url]"
		fi
		if [ "$print_raw" == "false" ]; then
			log "  $collection $url"
		else
			log "$collection"
		fi
	done
}

# Print help for the collectionlist command
function collection_list_help {
	log "  collection|c list|ls - List all collections"
	log "      Flags:"
	log "		-raw|-r - Print raw output"
}

# Short form of the collectionlist command
function collection_ls_command {
	collection_list_command $*
}

###END###
